name: Example Dependency Submission

on: push

permissions:
  contents: write

jobs:
  example-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: 20
      - name: Install NPM dependencies
        run: npm ci
      - name: Run all NPM build/test actions
        run: npm run --workspace example all
      - name: Run dependency submission
        uses: ./
        with:
          npm-package-directory: ./
