name: Publish

on:
  release:
    types: [created]

permissions:
  contents: read
  id-token: write # for provenance and publish access

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      - run: npm ci
      - run: npm test
      - run: npm version ${TAG_NAME} --git-tag-version=false --allow-same-version
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
      - run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ""
